/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GuideTaillesRouteImport } from './routes/guide-tailles'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as AdminLayoutProduitsSlugRouteImport } from './routes/admin/_layout/produits/$slug'
import { Route as AdminLayoutProduitsNewRouteImport } from './routes/admin/_layout/produits/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideTaillesRoute = GuideTaillesRouteImport.update({
  id: '/guide-tailles',
  path: '/guide-tailles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutProduitsSlugRoute = AdminLayoutProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProduitsNewRoute = AdminLayoutProduitsNewRouteImport.update({
  id: '/produits/new',
  path: '/produits/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/guide-tailles': typeof GuideTaillesRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/produits/$slug': typeof AdminLayoutProduitsSlugRoute
  '/admin/produits/new': typeof AdminLayoutProduitsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/guide-tailles': typeof GuideTaillesRoute
  '/admin/login': typeof AdminLoginRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/produits/$slug': typeof AdminLayoutProduitsSlugRoute
  '/admin/produits/new': typeof AdminLayoutProduitsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/guide-tailles': typeof GuideTaillesRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/produits/$slug': typeof AdminLayoutProduitsSlugRoute
  '/admin/_layout/produits/new': typeof AdminLayoutProduitsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/guide-tailles'
    | '/admin'
    | '/admin/login'
    | '/produit/$slug'
    | '/api/admin/upload'
    | '/admin/'
    | '/admin/produits/$slug'
    | '/admin/produits/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/guide-tailles'
    | '/admin/login'
    | '/produit/$slug'
    | '/api/admin/upload'
    | '/admin'
    | '/admin/produits/$slug'
    | '/admin/produits/new'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/guide-tailles'
    | '/admin/_layout'
    | '/admin/login'
    | '/produit/$slug'
    | '/api/admin/upload'
    | '/admin/_layout/'
    | '/admin/_layout/produits/$slug'
    | '/admin/_layout/produits/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  ContactRoute: typeof ContactRoute
  GuideTaillesRoute: typeof GuideTaillesRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide-tailles': {
      id: '/guide-tailles'
      path: '/guide-tailles'
      fullPath: '/guide-tailles'
      preLoaderRoute: typeof GuideTaillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/produits/$slug': {
      id: '/admin/_layout/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/admin/produits/$slug'
      preLoaderRoute: typeof AdminLayoutProduitsSlugRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/produits/new': {
      id: '/admin/_layout/produits/new'
      path: '/produits/new'
      fullPath: '/admin/produits/new'
      preLoaderRoute: typeof AdminLayoutProduitsNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutProduitsSlugRoute: typeof AdminLayoutProduitsSlugRoute
  AdminLayoutProduitsNewRoute: typeof AdminLayoutProduitsNewRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutProduitsSlugRoute: AdminLayoutProduitsSlugRoute,
  AdminLayoutProduitsNewRoute: AdminLayoutProduitsNewRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  ContactRoute: ContactRoute,
  GuideTaillesRoute: GuideTaillesRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
